name: Continuous Integration

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  DOTNET_VERSION: '5.0.301' # The .NET SDK version to use

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      working-directory: ./AccessAPI
      
    - name: Build 
      run: dotnet build --configuration Release
      working-directory: ./AccessAPI
    
    - name: Test
      run: dotnet test 
      working-directory: ./AccessAPI
